name: gRPC Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Set overall job timeout

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and run tests
      timeout-minutes: 5  # Set specific step timeout
      run: |
        # Build the test image
        docker build -t opensvm-grpc-test -f Dockerfile.test .
        
        # Run tests with resource limits and timeout
        docker run \
          --rm \
          --memory=2g \
          --cpus=2 \
          --name opensvm-grpc-test \
          opensvm-grpc-test \
          bash -c "timeout 45s ./scripts/run_grpc_tests_local.sh"
      
    - name: Upload test logs
      if: always()  # Upload logs even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: |
          zig-out/
          zig-cache/
